# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_USER: nordin
      MYSQL_ROOT_PASSWORD: nordin
      MYSQL_DATABASE: ecommerce
